#!/bin/bash
# -----------------------------------------------------------------------------
# docker-solder /start script
#
# Author:  Brian Eilber
# Updated: Jun 6th, 2015
# -----------------------------------------------------------------------------
USE_S3="false"
ACCESS_KEY=""
SECRET_KEY=""
BUCKET=""


if [ -f /configured ]
then
	CONFIGURED="true"
else
	CONFIGURED="false"
fi

if [ -z "$VIRTUAL_HOST" ]
then
	echo "VIRTUAL_HOST Must be defined"
	exit 1
fi
if [ -z "$TIME_ZONE" ]
then
	echo "TIME_ZONE not defined, defaulting to UTC"
	TIME_ZONE="UTC"
fi
if [ -z "$LANG" ]
then
        echo "LANG not defined, defaulting to en"
        LANG="en"
fi

CRYPT_KEY=`hostname | md5sum | cut -f 1 -d ' '`

if [ "$USE_S3" == "true" ]
then
	echo "S3 support wip disabled"
	
        exit 1
fi

while [ "$CONFIGURED" == false ]
do
	sed -i s,MIRROR_URL,${MIRROR_URL},g /TechnicSolder/app/config/solder.php
        sed -i s/USE_S3/${USE_S3}/g /TechnicSolder/app/config/solder.php
        sed -i s/ACCESS_KEY/${ACCESS_KEY}/g /TechnicSolder/app/config/solder.php
        sed -i s/SECRET_KEY/${SECRET_KEY}/g /TechnicSolder/app/config/solder.php
        sed -i s/BUCKET/${BUCKET}/g /TechnicSolder/app/config/solder.php
        sed -i s/VIRTUAL_HOST/${VIRTUAL_HOST}/g /TechnicSolder/app/config/app.php
        sed -i s/TIME_ZONE/${TIME_ZONE}/g /TechnicSolder/app/config/app.php
        sed -i s/LANG/${LANG}/g /TechnicSolder/app/config/app.php
	sed -i s/SUPASECRT/${CRYPT_KEY}/g /TechnicSolder/app/config/app.php
	sed -i s/POSTGRESQL_PORT_5432_TCP_ADDR/${POSTGRESQL_PORT_5432_TCP_ADDR}/g /TechnicSolder/app/config/database.php
	sed -i s/POSTGRESQL_ENV_DB_NAME/${POSTGRESQL_ENV_DB_NAME}/g /TechnicSolder/app/config/database.php
	sed -i s/POSTGRESQL_ENV_DB_USER/${POSTGRESQL_ENV_DB_USER}/g /TechnicSolder/app/config/database.php
	sed -i s/POSTGRESQL_ENV_DB_PASS/${POSTGRESQL_ENV_DB_PASS}/g /TechnicSolder/app/config/database.php
	sed -i s/REDISIO_PORT_6379_TCP_ADDR/${REDISIO_PORT_6379_TCP_ADDR}/g /TechnicSolder/app/config/database.php
	sed -i s/REDISIO_PORT_6379_TCP_PORT/${REDISIO_PORT_6379_TCP_PORT}/g /TechnicSolder/app/config/database.php
	CONFIGURED="true"
	touch /configured
done

cd /TechnicSolder

php artisan migrate:install
php artisan migrate

cp -v /etc/nginx/soldercore /etc/nginx/conf.d/default.conf

chown -R nginx.nginx /TechnicSolder
sed -i s/www-data/nginx/g /etc/php5/fpm/pool.d/www.conf
#echo "listen.mode = 0777" >> /etc/php5/fpm/pool.d/www.conf

/etc/init.d/php5-fpm start
